### ISSUE TITLE
new tool: the fuck

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pentoo/pentoo-historical#350]
```
https://github.com/nvbn/thefuck
```

Original issue reported on code.google.com by `sidhayn` on 20 Apr 2015 at 4:04

**Comment by blshkv** [comment]
I looked at the tool and can tell you that I don't like it. The name is offensive and the usability is very questionable. I suspect that the main audience of this tool are kids with the matrix screensaver  to feel "cool".

However, we already have a better software called bash-completion and it is enabled by default. Just press TAB before you completed a command, after it is completed and you will have no typos. This is a proper way.
