### ISSUE TITLE
upgrade compat-drivers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pentoo/pentoo-historical#91]
```
update grsec patches for compat-drivers 3.8_rc5

The livecd build is waiting on you ;-)
```

Original issue reported on code.google.com by `sidhayn` on 4 Feb 2013 at 5:50

**Comment by blshkv** [comment]
I guess I can close this bug as there is no more need in compat-drivers. We use the main kernel (and even not the latest most of the time)
